DEBUG_MODE = False
# SHOW_GRAPH = False
# GENEREATE_CLASS_FILE = False
# GENERATE_XES_FROM_INITIAL = False
# GENERATE_XES_FROM_CREATED = False
CLASS_MASK = set(
    [
        "ADD_RETURN_VALUE",
        "ADD_VARIABLE_VALUE",
        "AnnotationAddition",
        "ASSIGN_VARIABLE",
        "BlockAdd",
        "BlockRemove",
        "CHANGE_METHOD_INVOCATED",
        "CHANGE_VARIABLE_USED",
        "CHANGE_VARIABLE_VALUE",
        "ClassAdd",
        "ClassRemove",
        "COMMENT_ADDITION",
        "COMMENT_DELETION",
        "COMMENT_EDITION",
        "COMMENT_MOVED",
        "CONDITION",
        "CutPaste",
        "DeclarationStatementAdd",
        "DeclarationStatementRemove",
        "EmptyCommit",
        "EmptyLine",
        "ForAdd",
        "ForRemove",
        "IfAdd",
        "IfRemove",
        "FunctionAdd",
        "FunctionRemove",
        "ImportStatementAdd",
        "ImportStatementRemove",
        "InvocationStatementAdd",
        "InvocationStatementRemove",
        "LineBreakChange",
        "LineSpacingChange",
        "ModifyVariableValue",
        "NotSource",
        "PackageStatementAdd",
        "PackageStatementRemove",
        "RefactoringMiner",
        "RENAME_VARIABLE",
        "RENAME_FUNCTION",
        "REPLACE_FUNCTION",
        "REPLACE_METHOD",
        "ReturnStatementAdd",
        "ReturnStatementRemove",
        "STRING_EDITION",
        "MODIFY_VARIABLE_VALUE",
        "TrimEditionContent",
        "TRUE_TO_FALSE",
        "FALSE_TO_TRUE",
        "TYPO_ADD",
        "TYPO_DEL",
        "UNASSIGN_VARIABLE",
        "USE_NEW_VARIABLE",
        "USE_OLD_VARIABLE",
        "VariableAssignStatementAdd",
        "VariableAssignStatementRemove",
    ]
)
